# Generated by Django 5.0.6 on 2024-05-13 22:38

import api.apps
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('key', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('permission', models.IntegerField(choices=[(0, 'Admin'), (1, 'Moderator'), (2, 'Supporter'), (3, 'Public')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('version', models.CharField(default=api.apps.HexproofConfig.get_current_version, max_length=255)),
                ('uri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('supported', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('80', 'Eighty'), ('B', 'Bonus'), ('C', 'Common'), ('H', 'Half'), ('M', 'Mythic'), ('R', 'Rare'), ('S', 'Special'), ('T', 'Timeshifted'), ('U', 'Uncommon'), ('WM', 'Watermark')], max_length=12), blank=True, default=set, size=None)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.symbolset')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.TextField(blank=True, default='', null=True)),
                ('block_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('code_alt', models.CharField(blank=True, default='', max_length=255)),
                ('code_arena', models.CharField(blank=True, default='', max_length=255)),
                ('code_keyrune', models.CharField(blank=True, default='', max_length=255)),
                ('code_mtgo', models.CharField(blank=True, default='', max_length=255)),
                ('code_parent', models.CharField(blank=True, default='', max_length=255)),
                ('count_cards', models.IntegerField(default=0)),
                ('count_printed', models.IntegerField(blank=True, null=True)),
                ('count_tokens', models.IntegerField(default=0)),
                ('date_released', models.DateField()),
                ('id_cardmarket', models.IntegerField(blank=True, default=None, null=True)),
                ('id_cardmarket_extras', models.IntegerField(blank=True, default=None, null=True)),
                ('id_cardsphere', models.IntegerField(blank=True, default=None, null=True)),
                ('id_scryfall', models.TextField(unique=True)),
                ('id_tcgplayer', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.TextField()),
                ('name_cardmarket', models.TextField(blank=True, default='')),
                ('is_digital_only', models.BooleanField(default=False)),
                ('is_foil_only', models.BooleanField(default=False)),
                ('is_foreign_only', models.BooleanField(default=False)),
                ('is_nonfoil_only', models.BooleanField(default=False)),
                ('is_paper_only', models.BooleanField(default=False)),
                ('is_preview', models.BooleanField(default=False)),
                ('scryfall_icon_uri', models.TextField()),
                ('type', models.CharField(choices=[('core', 'Core'), ('expansion', 'Expansion'), ('masters', 'Masters'), ('alchemy', 'Alchemy'), ('masterpiece', 'Masterpiece'), ('arsenal', 'Arsenal'), ('from_the_vault', 'From The Vault'), ('spellbook', 'Spellbook'), ('premium_deck', 'Premium Deck'), ('duel_deck', 'Duel Deck'), ('draft_innovation', 'Draft Innovation'), ('treasure_chest', 'Treasure Chest'), ('commander', 'Commander'), ('planechase', 'Planechase'), ('archenemy', 'Archenemy'), ('vanguard', 'Vanguard'), ('funny', 'Funny'), ('starter', 'Starter'), ('box', 'Box'), ('promo', 'Promo'), ('token', 'Token'), ('memorabilia', 'Memorabilia'), ('minigame', 'Minigame')], default='expansion', max_length=255)),
                ('symbol', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.symbolset')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent_symbol_set', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.symbolset')),
            ],
        ),
    ]
