# Generated by Django 4.2.7 on 2023-12-04 23:16

from django.db import migrations


def create_symbol_rarities(apps, schema_editor):
    SymbolRarities = apps.get_model('hexproof', 'SymbolRarity')
    SymbolRarities.objects.create(code='WM', name='Watermark')
    SymbolRarities.objects.create(code='C', name='Common')
    SymbolRarities.objects.create(code='U', name='Uncommon')
    SymbolRarities.objects.create(code='R', name='Rare')
    SymbolRarities.objects.create(code='M', name='Mythic')
    SymbolRarities.objects.create(code='S', name='Special')
    SymbolRarities.objects.create(code='T', name='Timeshifted')
    SymbolRarities.objects.create(code='B', name='Bonus')
    SymbolRarities.objects.create(code='80', name='80')
    SymbolRarities.objects.create(code='H', name='Half')


class Migration(migrations.Migration):

    dependencies = [
        ('hexproof', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_symbol_rarities),
    ]
