# Generated by Django 4.2.8 on 2023-12-07 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hexproof.utils.project


class Migration(migrations.Migration):

    dependencies = [
        ('hexproof', '0002_set_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('mtgjson', 'MTGJSON'), ('scryfall', 'Scryfall'), ('sets', 'Sets'), ('symbols', 'Symbols')], max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('version', models.CharField(default=hexproof.utils.project.get_current_version, max_length=255)),
                ('uri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolCollectionWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('parent_symbol_set', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hexproof.symbolcollectionset')),
            ],
        ),
    ]
