# Generated by Django 4.2.8 on 2023-12-07 17:31

from django.db import migrations
from hexproof.apps import HexproofConfig


def create_meta_resources(apps, schema_editor):
    Meta = apps.get_model('hexproof', 'Meta')
    Meta.objects.create(resource='mtgjson', uri='https://mtgjson.com/api/v5')
    Meta.objects.create(resource='scryfall', uri='https://api.scryfall.com/bulk-data')
    Meta.objects.create(resource='sets', uri=str(HexproofConfig.API_URL / 'sets'))
    Meta.objects.create(resource='symbols', uri=str(HexproofConfig.API_URL / 'symbols'))


class Migration(migrations.Migration):

    dependencies = [
        ('hexproof', '0003_meta_symbolcollectionwatermark'),
    ]

    operations = [
        migrations.RunPython(create_meta_resources),
    ]
