# Generated by Django 4.2.8 on 2023-12-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexproof', '0004_meta_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolcollectionset',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hexproof.symbolcollectionset'),
        ),
    ]
