# Generated by Django 4.2.8 on 2023-12-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexproof', '0005_meta_uri_alter_meta_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='block',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='block_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='code_alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='code_arena',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='code_keyrune',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='code_mtgo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='code_parent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='name_cardmarket',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='set',
            name='type',
            field=models.CharField(choices=[('core', 'Core'), ('expansion', 'Expansion'), ('masters', 'Masters'), ('alchemy', 'Alchemy'), ('masterpiece', 'Masterpiece'), ('arsenal', 'Arsenal'), ('from_the_vault', 'From the Vault'), ('spellbook', 'Spellbook'), ('premium_deck', 'Premium Deck'), ('duel_deck', 'Duel Deck'), ('draft_innovation', 'Draft Innovation'), ('treasure_chest', 'Treasure Chest'), ('commander', 'Commander'), ('planechase', 'Planechase'), ('archenemy', 'Archenemy'), ('vanguard', 'Vanguard'), ('funny', 'Funny'), ('starter', 'Starter'), ('box', 'Box'), ('promo', 'Promo'), ('token', 'Token'), ('memorabilia', 'Memorabilia'), ('minigame', 'Minigame')], default='expansion', max_length=255),
        ),
        migrations.AlterField(
            model_name='symbolcollectionset',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hexproof.symbolcollectionset'),
        ),
    ]
